---
title: "STAT 380 Homework Exercises"
subtitle: "MDSR Chapter 05"
author: "Daniel Lee"
date: "Due: 27/01/2019"
output: html_notebook
---
  
# Front matter
  
```{r}
# always clean up R environment
rm(list = ls())

# load all packages here
library(mosaic)
library(Lahman)
library(tidyverse)
library(lubridate)
library(mdsr)
library(Hmisc)
library(readr)
head(Teams)
attach(Teams)
library(dplyr)
library(plyr)
library(xtable)
library(mosaicData)
library(tidyr)
```


# Exercises

### Exercise 5.2
```{r}
count_seasons <- function(teamname){
  Teams %>%
    subset(Teams, teamID == teamname) %>%
    count(Teams, teamID)}

```

### Exercise 5.3
```{r}
bk_teams <- 
  c("BR1", "BR2", "BR3", "BR4", "BRO", "BRP", "BRF")
bk_teams1 <- 
  sapply(FUN = bk_teams)
```

### Exercise 5.4
```{r}
Marriage %>%
  select(appdate, ceremonydate, dob) %>%
  glimpse()

Marriage %>%
  mutate(appdate = mdy(appdate), ceremonydate = mdy(ceremonydate), dob = mdy(dob)) %>%
  select(appdate, ceremonydate, dob)
```

### Exercise 5.5
```{r}

x1 <- c("1900.45", "$1900.45", "1,900.45", "nearly $2000") 
x2 <- as.factor(x1)
parse_number(x1)
as.factor(x2) 
```


### Exercise 5.6
```{r}
ds1 <- 
  tibble(
  id = c(1,2,3,1,2,3), 
  group = c("T", "T", "T", "C", "C", "C"), 
  vals = c(4.00, 6.00, 8.00, 5.00, 6.00, 10.00)
  )
ds1

tab <- xtable(ds1) 
print(tab, floating=FALSE)

Treat <- filter(ds1, group=="T") 
Control <- filter(ds1, group=="C") 
all <- mutate(Treat, diff = Treat$vals - Control$vals) 
all
```

### Exercise 5.7
```{r}
data_long <- 
  tibble(
  grp = c("A", "A", "B", "B"), 
  sex = c("F", "M", "F", "M"), 
  meanL = c(0.22, 0.47, 0.33, 0.55),
  sdL = c(0.11, 0.33, 0.11, 0.31),
  meanR = c(0.34, 0.57, 0.40, 0.65),
  sdR = c(0.08, 0.33, 0.07, 0.27)
  )

data_long

datawide <-
  data_long %>%
  spread(key = sex)

datawide
```

### Exercise 5.8
```{r}
dplyr::do(HELPrct)

```

### Exercise 5.12
```{r}
url <- "http://en.wikipedia.org/wiki/Mile_run_world_record_progression"
tables <- url %>%
  read_html() %>%
  html_nodes("table")
length(tables)

Table3 <- html_table(tables[[3]])
head(Table3)
```
